# Generated by Django 3.2.9 on 2021-11-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id']},
        ),
    ]
